upgrade doxygen to v1.9.5
aws/SigV4-for-AWS-IoT-embedded-sdk pull request #76
Opened 2022-12-22 00:45 UTC by adam-scislowicz

I've updated the doxygen task from using ubuntu 20.04 to ubuntu latest. In addition I've upgraded the docygen configuration for doxygen 1.9.5. Changes elsewhere have updated the docygen version referenced by two github actions to version 1.9.5

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

2022-12-22 00:58 UTC, kstribrnAmzn approved these changes

2022-12-22 18:09 UTC, kstribrnAmzn requested changes
You'll need to modify the doxygen comments on `SigV4CryptoInterface_t`. See [this failure](https://github.com/aws/SigV4-for-AWS-IoT-embedded-sdk/actions/runs/3753957369/jobs/6377728567).

Also this line needs it's python version updated to 3.11.0

2022-12-22 21:50 UTC, kstribrnAmzn approved these changes
You'll want to update your PRs description. Other than that it looks great!

2022-12-27 21:44 UTC, rawalexe approved these changes

2022-12-30 16:21 UTC, kstribrnAmzn approved these changes

2022-12-30 17:02 UTC, merged